-- ============================================================
-- 008_create_enrollment_functions.sql
--
-- INTENTIONALLY EMPTY — superseded by 000_combined_schema.sql
--
-- This migration originally created: enrollment helper functions.
-- 000_combined_schema.sql already creates all of it and is the source of
-- truth. Running both in order fails: 000 creates the objects, then this file
-- tried to create them again (e.g. `CREATE TYPE ... already exists`), which
-- aborted any rebuild of the migration chain from scratch.
--
-- The file is kept, not deleted: versions 000-011 are recorded in
-- supabase_migrations.schema_migrations on the remote databases, and removing
-- the file would leave that history referencing a migration that no longer
-- exists. Emptying it keeps history valid while letting a fresh database
-- build cleanly.
--
-- The original statements remain in git history and are duplicated verbatim
-- in 000_combined_schema.sql. Do not re-add DDL here — put schema changes in
-- a new timestamped migration.
-- ============================================================

-- No-op.
